### ISSUE TITLE
Cleanup wasm.ts in wasm-ast-types to generalize schema parsing

### ISSUE THREAD

**Issue by udit-gulati** [arufa-research/polar#113]
1. The InstantiateMsg, ExecuteMsg and QueryMsg are generated using https://www.npmjs.com/package/json-to-ts anf the Client objects are generated manually as structure is modified from above.

2. Update wasm.ts to only use https://www.npmjs.com/package/json-to-ts for schema values in Client objects too.

3. Test against astroport contracts https://github.com/astroport-fi/astroport-core to make sure that complex msg types parsing is working fine.

**Comment by amityadav0** [comment]
#114
