### ISSUE TITLE
Remove target/ and schema/ directories after polar compile

### ISSUE THREAD

**Issue by udit-gulati** [arufa-research/polar#60]
+ `target/` and `schema/` dir locations depend on Cargo.toml.
+ locate dirs and remove them.
+ only remove once checking artifacts dir has `.wasm` and schema `.json` files.

**Comment by coco-sha** [comment]
This was done intentionally because doing this will not be good in terms of time taken to recompile contracts

**Comment by udit-gulati** [comment]
Got it, and I'll add there 2 dirs to `.gitignore`.
